"""
pipeline_transforms.py
----------------------
18 preprocessing pipelines = 3 contrast × 6 edge-preserving filters.

Parameters are read from filter_params.json, generated by filtres.ipynb.
Workflow:
  1. Modify a filter parameter in filtres.ipynb
  2. Run the export cell (last cell of the notebook) → writes filter_params.json
  3. Launch training → new parameters are picked up automatically

If filter_params.json is absent, built-in defaults are used as fallback.
"""

import json
import cv2
import numpy as np
from pathlib import Path


# ── Parameter loading ─────────────────────────────────────────────────────────

_PARAMS_PATH = Path(__file__).parent / "filter_params.json"


def _load_params() -> dict:
    if _PARAMS_PATH.exists():
        try:
            params = json.loads(_PARAMS_PATH.read_text())
            print(f"  [pipeline_transforms] Paramètres chargés depuis {_PARAMS_PATH.name}")
            return params
        except Exception as e:
            print(f"  [pipeline_transforms] Erreur lecture {_PARAMS_PATH.name}: {e} — défauts utilisés")
    else:
        print(f"  [pipeline_transforms] {_PARAMS_PATH.name} introuvable — défauts utilisés")
        print(f"    → Lancez la cellule d'export de filtres.ipynb pour synchroniser les paramètres.")
    return {}


_NB = _load_params()


def _p(filter_name: str, key: str, default):
    """Return parameter from filter_params.json or default."""
    return _NB.get(filter_name, {}).get(key, default)


# ══════════════════════════════════════════════════════════════════════════════
# Step 1 — Contrast Enhancement
# ══════════════════════════════════════════════════════════════════════════════

def contrast_clahe(img_rgb: np.ndarray) -> np.ndarray:
    clip = float(_p("clahe", "clip_limit", 2.0))
    tile = int(_p("clahe", "tile_size", 8))
    lab  = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2LAB)
    clahe = cv2.createCLAHE(clipLimit=clip, tileGridSize=(tile, tile))
    lab[:, :, 0] = clahe.apply(lab[:, :, 0])
    return cv2.cvtColor(lab, cv2.COLOR_LAB2RGB)


def contrast_original(img_rgb: np.ndarray) -> np.ndarray:
    return img_rgb.copy()


def contrast_retinex(img_rgb: np.ndarray) -> np.ndarray:
    sigmas  = tuple(float(s) for s in _p("retinex", "sigmas", (25.0, 50.0, 100.0)))
    img_f   = img_rgb.astype(np.float32) + 1.0
    msr     = np.zeros_like(img_f)
    max_s   = min(img_f.shape[:2]) / 6.0
    for s in sigmas:
        blurred = cv2.GaussianBlur(img_f, (0, 0), min(float(s), max_s))
        msr    += np.log(img_f) - np.log(blurred + 1e-6)
    msr /= len(sigmas)
    out = np.zeros_like(img_f)
    for c in range(3):
        ch = msr[:, :, c]
        lo, hi = ch.min(), ch.max()
        out[:, :, c] = (ch - lo) / (hi - lo + 1e-6) * 255.0
    return out.clip(0, 255).astype(np.uint8)


# ══════════════════════════════════════════════════════════════════════════════
# Step 2 — Edge-Preserving Filters
# ══════════════════════════════════════════════════════════════════════════════

def filter_bilateral(img_rgb: np.ndarray) -> np.ndarray:
    d  = int(_p("bilateral", "d", 50))
    sc = float(_p("bilateral", "sigmaColor", 20))
    ss = float(_p("bilateral", "sigmaSpace", 100))
    bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
    out = cv2.bilateralFilter(bgr, d=d, sigmaColor=sc, sigmaSpace=ss)
    return cv2.cvtColor(out, cv2.COLOR_BGR2RGB)


def filter_nlm(img_rgb: np.ndarray) -> np.ndarray:
    h    = float(_p("nlm", "h", 10))
    tmpl = int(_p("nlm", "templateWindowSize", 7))
    srch = int(_p("nlm", "searchWindowSize", 21))
    bgr  = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
    out  = cv2.fastNlMeansDenoisingColored(bgr, None,
                                           h=h, hColor=h,
                                           templateWindowSize=tmpl,
                                           searchWindowSize=srch)
    return cv2.cvtColor(out, cv2.COLOR_BGR2RGB)


def filter_bm3d(img_rgb: np.ndarray) -> np.ndarray:
    import bm3d as _bm3d
    sigma = float(_p("bm3d", "sigma", 25)) / 255.0
    img_f = img_rgb.astype(np.float32) / 255.0
    out   = np.zeros_like(img_f)
    for c in range(3):
        out[:, :, c] = _bm3d.bm3d(img_f[:, :, c], sigma_psd=sigma)
    return (out.clip(0.0, 1.0) * 255.0).astype(np.uint8)


def filter_snn(img_rgb: np.ndarray) -> np.ndarray:
    """
    SNN par plage d'intensité — algorithme du notebook filtres.ipynb.
    Pour chaque pixel c, retient les voisins dans [c-h, c+h] et les moyenne.
    Appliqué canal par canal.
    """
    radius = int(_p("snn", "radius", 2))
    h_val  = float(_p("snn", "h", 5))
    passes = int(_p("snn", "passes", 1))

    result = img_rgb.copy()
    for _ in range(passes):
        img_f = result.astype(np.float32)
        win   = 2 * radius + 1
        out   = np.empty_like(img_f)
        for c in range(3):
            ch  = img_f[:, :, c]
            pad = cv2.copyMakeBorder(ch, radius, radius, radius, radius, cv2.BORDER_REFLECT)
            H, W = ch.shape
            planes = np.stack([
                pad[dy:dy+H, dx:dx+W]
                for dy in range(win) for dx in range(win)
                if not (dy == radius and dx == radius)
            ])                                       # (n_nbrs, H, W)
            keep   = np.abs(planes - ch) <= h_val    # boolean mask
            n_kept = keep.sum(axis=0)
            accum  = (planes * keep).sum(axis=0)
            out[:, :, c] = np.where(n_kept > 0, accum / np.maximum(n_kept, 1), ch)
        result = np.clip(out, 0, 255).astype(np.uint8)
    return result


def filter_kramer_bruckner(img_rgb: np.ndarray) -> np.ndarray:
    win   = int(_p("kb", "win", 1))
    iters = int(_p("kb", "iters", 1))
    k      = 2 * win + 1
    kernel = np.ones((k, k), np.uint8)
    result = img_rgb.copy()
    for _ in range(iters):
        img_f     = result.astype(np.float32)
        local_min = cv2.erode(img_f,  kernel)
        local_max = cv2.dilate(img_f, kernel)
        midpoint  = (local_max + local_min) / 2.0
        out       = local_min.copy()
        out[img_f > midpoint] = local_max[img_f > midpoint]
        result    = np.clip(out, 0, 255).astype(np.uint8)
    return result


def filter_epoaf(img_rgb: np.ndarray) -> np.ndarray:
    offsets = tuple(float(o) for o in _p("epoaf", "offsets", (-2.0, -1.0, 1.0, 2.0)))
    ksize   = int(_p("epoaf", "ksize", 3))
    img_f = img_rgb.astype(np.float32)
    gray  = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY).astype(np.float32)
    gx    = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=ksize)
    gy    = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=ksize)
    mag   = np.sqrt(gx**2 + gy**2) + 1e-6
    tx = -gy / mag
    ty =  gx / mag
    H, W = gray.shape
    base_x, base_y = np.meshgrid(np.arange(W, dtype=np.float32),
                                  np.arange(H, dtype=np.float32))
    bgr   = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
    accum = img_f.copy()
    for s in offsets:
        map_x       = (base_x + tx * s).clip(0, W - 1)
        map_y       = (base_y + ty * s).clip(0, H - 1)
        sampled_bgr = cv2.remap(bgr, map_x, map_y, cv2.INTER_LINEAR)
        accum      += cv2.cvtColor(sampled_bgr, cv2.COLOR_BGR2RGB).astype(np.float32)
    return (accum / (1 + len(offsets))).clip(0, 255).astype(np.uint8)


# ══════════════════════════════════════════════════════════════════════════════
# Pipeline registry
# ══════════════════════════════════════════════════════════════════════════════

CONTRAST_STEPS = {
    "original": contrast_original,
    "clahe":    contrast_clahe,
    "retinex":  contrast_retinex,
}

EDGE_STEPS = {
    "bilateral":       filter_bilateral,
    "nlm":             filter_nlm,
    "kramer_bruckner": filter_kramer_bruckner,
    "epoaf":           filter_epoaf,
    "snn":             filter_snn,
    "bm3d":            filter_bm3d,
}

PIPELINES: dict[str, tuple] = {}
for _c, _cfn in CONTRAST_STEPS.items():
    for _e, _efn in EDGE_STEPS.items():
        PIPELINES[f"{_c}_{_e}"] = (_cfn, _efn)

_FAST = ["bilateral", "nlm", "kramer_bruckner", "epoaf"]
_SLOW = ["snn", "bm3d"]
PIPELINE_NAMES = (
    [f"{c}_{e}" for c in CONTRAST_STEPS for e in _FAST] +
    [f"{c}_{e}" for c in CONTRAST_STEPS for e in _SLOW]
)


def apply_pipeline(img_rgb: np.ndarray, name: str) -> np.ndarray:
    """Apply the named pipeline (contrast → edge filter) to an RGB uint8 image."""
    c_fn, e_fn = PIPELINES[name]
    return e_fn(c_fn(img_rgb))


def pipeline_label(name: str) -> str:
    """Human-readable label, e.g. 'CLAHE + Bilateral'."""
    c, e = name.split("_", 1)
    C = {"original": "Original", "clahe": "CLAHE", "retinex": "Retinex"}
    E = {"bilateral": "Bilateral", "nlm": "NLM", "bm3d": "BM3D",
         "snn": "SNN", "kramer_bruckner": "Kramer-Bruckner", "epoaf": "EPOAF"}
    return f"{C.get(c, c)} + {E.get(e, e)}"


if __name__ == "__main__":
    test_img = np.random.randint(0, 255, (64, 64, 3), dtype=np.uint8)
    for name in PIPELINE_NAMES:
        out = apply_pipeline(test_img, name)
        assert out.shape == test_img.shape and out.dtype == np.uint8, \
            f"Pipeline {name} returned bad shape/dtype"
        print(f"  {name:35s} OK  mean={out.mean():.1f}")
    print(f"\nAll {len(PIPELINE_NAMES)} pipelines OK.")
