"""
pipeline_transforms.py
----------------------
18 preprocessing pipelines = 3 contrast × 6 edge-preserving filters.

Implementations are ported directly from filtres.ipynb (source of truth).
Images are grayscale camera frames stored as 3-channel RGB (all channels equal),
so each filter is applied on a single luminance channel then restacked.

Parameters are read from filter_params.json, generated by the export cell
in filtres.ipynb.  If absent, built-in defaults matching the notebook are used.
"""

import json
import cv2
import numpy as np
from pathlib import Path
from scipy.fftpack import dct, idct


# ── Parameter loading ─────────────────────────────────────────────────────────

_PARAMS_PATH = Path(__file__).parent / "filter_params.json"


def _load_params() -> dict:
    if _PARAMS_PATH.exists():
        try:
            params = json.loads(_PARAMS_PATH.read_text())
            print(f"  [pipeline_transforms] Paramètres chargés depuis {_PARAMS_PATH.name}")
            return params
        except Exception as e:
            print(f"  [pipeline_transforms] Erreur lecture {_PARAMS_PATH.name}: {e} — défauts utilisés")
    else:
        print(f"  [pipeline_transforms] {_PARAMS_PATH.name} introuvable — défauts utilisés")
    return {}


_NB = _load_params()


def _p(filter_name: str, key: str, default):
    return _NB.get(filter_name, {}).get(key, default)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _to_gray(img_rgb: np.ndarray) -> np.ndarray:
    """Extract luminance channel (images are grayscale stored as RGB)."""
    return img_rgb[:, :, 0]


def _to_rgb(gray: np.ndarray) -> np.ndarray:
    """Stack single channel back to 3-channel RGB."""
    return np.stack([gray, gray, gray], axis=2)


# ══════════════════════════════════════════════════════════════════════════════
# Step 1 — Contrast Enhancement  (ported from filtres.ipynb)
# ══════════════════════════════════════════════════════════════════════════════

def contrast_original(img_rgb: np.ndarray) -> np.ndarray:
    return img_rgb.copy()


def contrast_clahe(img_rgb: np.ndarray) -> np.ndarray:
    """CLAHE applied directly on the grayscale channel (notebook cell: clahe_code)."""
    clip = float(_p("clahe", "clip_limit", 1.0))
    tile = int(_p("clahe", "tile_size", 32))
    gray  = _to_gray(img_rgb)
    clahe = cv2.createCLAHE(clipLimit=clip, tileGridSize=(tile, tile))
    return _to_rgb(clahe.apply(gray))


def contrast_retinex(img_rgb: np.ndarray) -> np.ndarray:
    """Multi-Scale Retinex on grayscale (notebook cell: retinex_code / apply_retinex)."""
    sigmas = tuple(float(s) for s in _p("retinex", "sigmas", (15,)))
    gray   = _to_gray(img_rgb).astype(np.float32)
    img_f  = gray + 1.0
    log_img = np.log(img_f)
    msr    = np.zeros_like(img_f)
    for sigma in sigmas:
        blurred = cv2.GaussianBlur(img_f, (0, 0), float(sigma))
        blurred = np.maximum(blurred, 1.0)
        msr    += log_img - np.log(blurred)
    msr /= len(sigmas)
    out = cv2.normalize(msr, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    return _to_rgb(out)


# ══════════════════════════════════════════════════════════════════════════════
# Step 2 — Edge-Preserving Filters  (ported from filtres.ipynb)
# ══════════════════════════════════════════════════════════════════════════════

def filter_bilateral(img_rgb: np.ndarray) -> np.ndarray:
    """Bilateral filter on grayscale (notebook cell: c825c341)."""
    d  = int(_p("bilateral", "d", 110))
    sc = float(_p("bilateral", "sigmaColor", 20))
    ss = float(_p("bilateral", "sigmaSpace", 50))
    gray = _to_gray(img_rgb)
    out  = cv2.bilateralFilter(gray, d=d, sigmaColor=sc, sigmaSpace=ss)
    return _to_rgb(out)


def filter_nlm(img_rgb: np.ndarray) -> np.ndarray:
    """Non-Local Means denoising on grayscale (notebook cell: 5afe7920)."""
    h    = float(_p("nlm", "h", 5))
    tmpl = int(_p("nlm", "templateWindowSize", 11))
    srch = int(_p("nlm", "searchWindowSize", 27))
    gray = _to_gray(img_rgb)
    out  = cv2.fastNlMeansDenoising(gray, h=h,
                                    templateWindowSize=tmpl,
                                    searchWindowSize=srch)
    return _to_rgb(out)


def filter_snn(img_rgb: np.ndarray) -> np.ndarray:
    """SNN intensity-range filter on grayscale (notebook cell: 15163dac / apply_snn)."""
    radius = int(_p("snn", "radius", 2))
    h_val  = float(_p("snn", "h", 5))
    passes = int(_p("snn", "passes", 1))

    gray   = _to_gray(img_rgb)
    result = gray.copy()

    for _ in range(passes):
        img_f = result.astype(np.float32)
        win   = 2 * radius + 1
        H, W  = img_f.shape
        pad   = cv2.copyMakeBorder(img_f, radius, radius, radius, radius,
                                   cv2.BORDER_REFLECT)
        planes = np.stack([
            pad[dy:dy+H, dx:dx+W]
            for dy in range(win) for dx in range(win)
            if not (dy == radius and dx == radius)
        ])                                        # (n_nbrs, H, W)
        keep   = np.abs(planes - img_f) <= h_val  # boolean mask
        n_kept = keep.sum(axis=0)
        accum  = (planes * keep).sum(axis=0)
        out    = np.where(n_kept > 0, accum / np.maximum(n_kept, 1), img_f)
        result = np.clip(out, 0, 255).astype(np.uint8)

    return _to_rgb(result)


def filter_kramer_bruckner(img_rgb: np.ndarray) -> np.ndarray:
    """Kramer-Bruckner morphological filter on grayscale (notebook cell: ce00142b / kb_filter)."""
    win   = int(_p("kb", "win", 1))
    iters = int(_p("kb", "iters", 1))
    k      = 2 * win + 1
    kernel = np.ones((k, k), np.uint8)
    result = _to_gray(img_rgb)
    for _ in range(iters):
        img_f     = result.astype(np.float32)
        local_min = cv2.erode(img_f,  kernel)
        local_max = cv2.dilate(img_f, kernel)
        midpoint  = (local_max + local_min) / 2.0
        out       = local_min.copy()
        out[img_f > midpoint] = local_max[img_f > midpoint]
        result    = np.clip(out, 0, 255).astype(np.uint8)
    return _to_rgb(result)


def filter_epoaf(img_rgb: np.ndarray) -> np.ndarray:
    """EPOAF tangential smoothing on grayscale (notebook cell: 5b2a7b4f / apply_epoaf)."""
    offsets = tuple(float(o) for o in _p("epoaf", "offsets", (-1.0, 1.0)))
    ksize   = int(_p("epoaf", "ksize", 5))

    gray  = _to_gray(img_rgb).astype(np.float32)
    H, W  = gray.shape
    gx    = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=ksize)
    gy    = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=ksize)
    mag   = np.sqrt(gx**2 + gy**2) + 1e-6
    tx    = -gy / mag
    ty    =  gx / mag
    xs    = np.tile(np.arange(W, dtype=np.float32)[None, :], (H, 1))
    ys    = np.tile(np.arange(H, dtype=np.float32)[:, None], (1, W))
    accum = gray.copy()
    n     = 1
    for s in offsets:
        map_x  = np.clip(xs + s * tx, 0, W - 1).astype(np.float32)
        map_y  = np.clip(ys + s * ty, 0, H - 1).astype(np.float32)
        accum += cv2.remap(gray, map_x, map_y, cv2.INTER_LINEAR,
                           borderMode=cv2.BORDER_REFLECT)
        n += 1
    out = np.clip(accum / n, 0, 255).astype(np.uint8)
    return _to_rgb(out)


def filter_bm3d(img_rgb: np.ndarray) -> np.ndarray:
    """
    BM3D custom implementation ported from filtres.ipynb (cell: bm3d_functions).
    Two-pass algorithm: hard-thresholding DCT (Step 1) + Wiener filtering (Step 2).
    Operates on grayscale float64, normalises output to [0, 255].
    """
    sigma = float(_p("bm3d", "sigma", 4))

    # ── BM3D hyper-parameters (matching filtres.ipynb globals) ──────────────
    lamb2d             = 2.0
    lamb3d             = 2.7
    Step1_ThreDist     = 1000
    Step1_MaxMatch     = 16
    Step1_BlockSize    = 8
    Step1_spdup_factor = 3
    Step1_WindowSize   = 39
    Step2_ThreDist     = 200
    Step2_MaxMatch     = 32
    Step2_BlockSize    = 8
    Step2_spdup_factor = 3
    Step2_WindowSize   = 39
    Kaiser_Window_beta = 2.0

    # ── Internal helpers (identical to notebook) ─────────────────────────────

    def _init(img, block_size):
        w      = np.kaiser(block_size, Kaiser_Window_beta)
        kaiser = np.outer(w, w)
        return np.zeros(img.shape), np.zeros(img.shape), kaiser

    def _search_window(img, ref, block_size, win_size):
        M = np.zeros((2, 2), dtype=int)
        M[0, 0] = max(0, ref[0] + int((block_size - win_size) / 2))
        M[0, 1] = max(0, ref[1] + int((block_size - win_size) / 2))
        M[1, 0] = M[0, 0] + win_size
        M[1, 1] = M[0, 1] + win_size
        if M[1, 0] >= img.shape[0]:
            M[1, 0] = img.shape[0] - 1
            M[0, 0] = max(0, M[1, 0] - win_size)
        if M[1, 1] >= img.shape[1]:
            M[1, 1] = img.shape[1] - 1
            M[0, 1] = max(0, M[1, 1] - win_size)
        return M

    def _dct2(a):
        return dct(dct(a, axis=0, norm='ortho'), axis=1, norm='ortho')

    def _idct2(a):
        return idct(idct(a, axis=0, norm='ortho'), axis=1, norm='ortho')

    def _pre_dct(img, block_size):
        out = np.zeros((img.shape[0] - block_size,
                        img.shape[1] - block_size,
                        block_size, block_size))
        for i in range(out.shape[0]):
            for j in range(out.shape[1]):
                out[i, j] = _dct2(img[i:i+block_size, j:j+block_size].astype(np.float64))
        return out

    # ── Step 1 ────────────────────────────────────────────────────────────────

    def _s1_dist(dct1, dct2):
        bs = dct1.shape[0]
        d1, d2 = dct1.copy(), dct2.copy()
        if sigma > 40:
            thr = lamb2d * sigma
            d1[np.abs(d1) < thr] = 0
            d2[np.abs(d2) < thr] = 0
        return np.linalg.norm(d1 - d2) ** 2 / (bs ** 2)

    def _s1_group(noisy, ref, dct_all, bs, thr_dist, max_match, win_size):
        WL  = _search_window(noisy, ref, bs, win_size)
        N   = (win_size - bs + 1) ** 2
        pos = np.zeros((N, 2), dtype=int)
        grp = np.zeros((N, bs, bs))
        dst = np.zeros(N)
        ref_dct = dct_all[ref[0], ref[1]]
        cnt = 0
        for i in range(win_size - bs + 1):
            for j in range(win_size - bs + 1):
                sd = dct_all[WL[0,0]+i, WL[0,1]+j]
                d  = _s1_dist(ref_dct, sd)
                if d < thr_dist:
                    pos[cnt] = [WL[0,0]+i, WL[0,1]+j]
                    grp[cnt] = sd
                    dst[cnt] = d
                    cnt += 1
        if cnt <= max_match:
            return pos[:cnt], grp[:cnt]
        idx = np.argpartition(dst[:cnt], max_match)
        return pos[idx[:max_match]], grp[idx[:max_match]]

    def _s1_filter(grp):
        thr = lamb3d * sigma
        nz  = 0
        for i in range(grp.shape[1]):
            for j in range(grp.shape[2]):
                v = dct(grp[:, i, j], norm='ortho')
                v[np.abs(v) < thr] = 0.0
                nz += np.count_nonzero(v)
                grp[:, i, j] = idct(v, norm='ortho')
        return grp, nz

    def _s1_aggregate(grp, pos, basic_img, basic_wt, kaiser, nz):
        w = (1.0 if nz < 1 else 1.0 / (sigma ** 2 * nz)) * kaiser
        for i in range(pos.shape[0]):
            r, c   = pos[i, 0], pos[i, 1]
            s1, s2 = grp.shape[1], grp.shape[2]
            basic_img[r:r+s1, c:c+s2] += w * _idct2(grp[i])
            basic_wt [r:r+s1, c:c+s2] += w

    def _bm3d_step1(noisy):
        basic_img, basic_wt, kaiser = _init(noisy, Step1_BlockSize)
        dct_all = _pre_dct(noisy, Step1_BlockSize)
        for i in range(int((noisy.shape[0] - Step1_BlockSize) / Step1_spdup_factor) + 2):
            for j in range(int((noisy.shape[1] - Step1_BlockSize) / Step1_spdup_factor) + 2):
                ref = [
                    min(Step1_spdup_factor * i, noisy.shape[0] - Step1_BlockSize - 1),
                    min(Step1_spdup_factor * j, noisy.shape[1] - Step1_BlockSize - 1),
                ]
                pos, grp = _s1_group(noisy, ref, dct_all,
                                     Step1_BlockSize, Step1_ThreDist,
                                     Step1_MaxMatch,  Step1_WindowSize)
                grp, nz  = _s1_filter(grp)
                _s1_aggregate(grp, pos, basic_img, basic_wt, kaiser, nz)
        basic_img /= np.where(basic_wt == 0, 1, basic_wt)
        return basic_img

    # ── Step 2 ────────────────────────────────────────────────────────────────

    def _s2_dist(basic, p1, p2, bs):
        B1 = basic[p1[0]:p1[0]+bs, p1[1]:p1[1]+bs].astype(np.float64)
        B2 = basic[p2[0]:p2[0]+bs, p2[1]:p2[1]+bs].astype(np.float64)
        return np.linalg.norm(B1 - B2) ** 2 / (bs ** 2)

    def _s2_group(basic, noisy, ref, bs, thr_dist, max_match, win_size,
                  dct_basic, dct_noisy):
        WL  = _search_window(basic, ref, bs, win_size)
        N   = (win_size - bs + 1) ** 2
        pos = np.zeros((N, 2), dtype=int)
        dst = np.zeros(N)
        cnt = 0
        for i in range(win_size - bs + 1):
            for j in range(win_size - bs + 1):
                sp = [WL[0,0]+i, WL[0,1]+j]
                d  = _s2_dist(basic, ref, sp, bs)
                if d < thr_dist:
                    pos[cnt] = sp
                    dst[cnt] = d
                    cnt += 1
        if cnt <= max_match:
            pos = pos[:cnt]
        else:
            pos = pos[np.argpartition(dst[:cnt], max_match)[:max_match]]
        n = pos.shape[0]
        grp_b = np.zeros((n, bs, bs))
        grp_n = np.zeros((n, bs, bs))
        for i in range(n):
            r, c     = pos[i]
            grp_b[i] = dct_basic[r, c]
            grp_n[i] = dct_noisy[r, c]
        return pos, grp_b, grp_n

    def _s2_filter(grp_b, grp_n):
        weight = 0
        coef   = 1.0 / grp_n.shape[0]
        for i in range(grp_n.shape[1]):
            for j in range(grp_n.shape[2]):
                vb = dct(grp_b[:, i, j], norm='ortho')
                vn = dct(grp_n[:, i, j], norm='ortho')
                vw = vb ** 2 * coef
                vw /= (vw + sigma ** 2)
                vn *= vw
                weight += np.sum(vw)
                grp_n[:, i, j] = idct(vn, norm='ortho')
        ww = 1.0 / (sigma ** 2 * weight) if weight > 0 else 1.0
        return grp_n, ww

    def _s2_aggregate(grp_n, ww, pos, final_img, final_wt, kaiser):
        w = ww * kaiser
        for i in range(pos.shape[0]):
            r, c   = pos[i, 0], pos[i, 1]
            s1, s2 = grp_n.shape[1], grp_n.shape[2]
            final_img[r:r+s1, c:c+s2] += w * _idct2(grp_n[i])
            final_wt [r:r+s1, c:c+s2] += w

    def _bm3d_step2(basic, noisy):
        final_img, final_wt, kaiser = _init(basic, Step2_BlockSize)
        dct_noisy = _pre_dct(noisy, Step2_BlockSize)
        dct_basic = _pre_dct(basic, Step2_BlockSize)
        for i in range(int((basic.shape[0] - Step2_BlockSize) / Step2_spdup_factor) + 2):
            for j in range(int((basic.shape[1] - Step2_BlockSize) / Step2_spdup_factor) + 2):
                ref = [
                    min(Step2_spdup_factor * i, basic.shape[0] - Step2_BlockSize - 1),
                    min(Step2_spdup_factor * j, basic.shape[1] - Step2_BlockSize - 1),
                ]
                pos, grp_b, grp_n = _s2_group(basic, noisy, ref,
                                              Step2_BlockSize, Step2_ThreDist,
                                              Step2_MaxMatch,  Step2_WindowSize,
                                              dct_basic, dct_noisy)
                grp_n, ww = _s2_filter(grp_b, grp_n)
                _s2_aggregate(grp_n, ww, pos, final_img, final_wt, kaiser)
        final_img /= np.where(final_wt == 0, 1, final_wt)
        return final_img

    # ── Run ───────────────────────────────────────────────────────────────────
    gray    = _to_gray(img_rgb).astype(np.float64)
    basic   = _bm3d_step1(gray)
    final   = _bm3d_step2(basic, gray)
    out     = np.zeros(gray.shape, dtype=np.float64)
    cv2.normalize(final, out, 0, 255, cv2.NORM_MINMAX, dtype=-1)
    return _to_rgb(out.astype(np.uint8))


# ══════════════════════════════════════════════════════════════════════════════
# Pipeline registry
# ══════════════════════════════════════════════════════════════════════════════

CONTRAST_STEPS = {
    "original": contrast_original,
    "clahe":    contrast_clahe,
    "retinex":  contrast_retinex,
}

EDGE_STEPS = {
    "bilateral":       filter_bilateral,
    "nlm":             filter_nlm,
    "kramer_bruckner": filter_kramer_bruckner,
    "epoaf":           filter_epoaf,
    "snn":             filter_snn,
    "bm3d":            filter_bm3d,
}

PIPELINES: dict[str, tuple] = {}
for _c, _cfn in CONTRAST_STEPS.items():
    for _e, _efn in EDGE_STEPS.items():
        PIPELINES[f"{_c}_{_e}"] = (_cfn, _efn)

_FAST = ["bilateral", "nlm", "kramer_bruckner", "epoaf"]
_SLOW = ["snn", "bm3d"]
PIPELINE_NAMES = (
    [f"{c}_{e}" for c in CONTRAST_STEPS for e in _FAST] +
    [f"{c}_{e}" for c in CONTRAST_STEPS for e in _SLOW]
)


def apply_pipeline(img_rgb: np.ndarray, name: str) -> np.ndarray:
    """Apply the named pipeline (contrast → edge filter) to an RGB uint8 image."""
    c_fn, e_fn = PIPELINES[name]
    return e_fn(c_fn(img_rgb))


def pipeline_label(name: str) -> str:
    c, e = name.split("_", 1)
    C = {"original": "Original", "clahe": "CLAHE", "retinex": "Retinex"}
    E = {"bilateral": "Bilateral", "nlm": "NLM", "bm3d": "BM3D",
         "snn": "SNN", "kramer_bruckner": "Kramer-Bruckner", "epoaf": "EPOAF"}
    return f"{C.get(c, c)} + {E.get(e, e)}"


if __name__ == "__main__":
    test_img = np.random.randint(0, 255, (64, 64, 3), dtype=np.uint8)
    for name in PIPELINE_NAMES:
        out = apply_pipeline(test_img, name)
        assert out.shape == test_img.shape and out.dtype == np.uint8, \
            f"Pipeline {name} returned bad shape/dtype"
        print(f"  {name:35s} OK  mean={out.mean():.1f}")
    print(f"\nAll {len(PIPELINE_NAMES)} pipelines OK.")
